{
 "title": "NVIDIA GPU Metrics",
 "description": "NVIDIA GPU Metrics",
 "tags": [ "GPU" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": "{\"find\": \"terms\", \"field\": \"node.keyword\"}"
   },
   {
    "name": "GPU",
    "query": "{\"find\": \"terms\", \"field\": \"gpu_id.keyword\", \"query\": \"node:$Server\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "#GPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 10, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "gpu_serial",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total GPU Utilization (Avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "utilization.gpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "node:$Server",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total GPU Memory Utilization (Avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "utilization.memory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "node:$Server",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Total Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 10, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "node:$Server",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 10, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory.used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "node:$Server",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Power Draw (Avg)",
   "type": "graph",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported.\nThis reading is accurate to within +/- 5 watts.\nRequires Inforom PWR object version 3.0 or higher or  Kepler device.",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "power.draw",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "node:$Server",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Temperature (Avg)",
   "type": "graph",
   "description": "Core GPU temperature. For all discrete and S-class products.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "temperature.gpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "node:$Server",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "#Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 10, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "node.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Per Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-utilization",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "utilization.gpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 10, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 10, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "utilization.memory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Power Draw",
   "type": "graph",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported.\nThis reading is accurate to within +/- 5 watts.\nRequires Inforom PWR object version 3.0 or higher or  Kepler device.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "power.draw",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "description": "Core GPU temperature. For all discrete and S-class products.",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 10, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 10, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "temperature.gpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Performance (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "utilization.gpu",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Memory (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "utilization.memory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "gpu_name.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "driver_version",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "pstate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Graphics MHz",
   "type": "graph",
   "description": "Current frequency of graphics (shader) clock",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "clocks.current.graphics",
       "id": "1",
       "inlineScript": "_value * 1000000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000000" } },
       "type": "max"
      },
      {
       "field": "clocks.max.graphics",
       "id": "3",
       "inlineScript": "_value * 1000000",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1000000" } },
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Total Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "memory.used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Apps Running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-Running Apps",
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "4",
       "settings": { "min_doc_count": 50, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 50, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ECC Errors",
   "type": "graph",
   "description": "Total errors detected across entire chip. Sum of Device  Memory, Register File, L1 Cache, L2 Cache and Texture Memory",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ecc.errors.corrected.aggregate.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "ecc.errors.uncorrected.aggregate.total",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Performance State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{node.keyword}}-{{gpu_id.keyword}}-{{field}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "pstate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GPU Apps",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "gpu_id.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "process_name.keyword",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pid",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "used_gpu_memory",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "pid",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "node:$Server  AND gpu_id:$GPU",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}